[package]
name = "insonnia"
version = "0.2.2"
authors = ["Francesco Barresi <cesco.barresi@gmail.com>"]

[dependencies]
getopts = "~0.2"
eui48 = "0.1.0"
csv = "~1.0.0-beta.5"
rand = "0.3"
log = "~0.3"
simplelog = "~0.5"
